# Module
# https://gohugo.io/hugo-modules/configuration/
# https://www.thenewdynamic.com/article/hugo-modules-everything-from-imports-to-create/
# ################################

mounts:
  - source: layouts
    target: layouts
  # Returning partials are core elements which should sit at the root of the project.
  - source: func
    target: layouts/partials/func
  # Huge's config is mounted in the assets directory
  - source: assets
    target: assets
  - source: _huge
    target: assets/_huge
  - source: content/en
    target: content
    lang: en
  - source: _prebuild/public
    target: content
    lang: en
    excludeFiles: 
    - data/params.json
  - source: data
    target: data
  - source: _prebuild/public/data
    target: data
imports:
  - path: github.com/theNewDynamic/huge
  - path: github.com/theNewDynamic/hugo-module-tnd-menus
  - path: github.com/theNewDynamic/hugo-module-tnd-socials
  - path: github.com/theNewDynamic/hugo-module-tnd-headers
  - path: github.com/theNewDynamic/hugo-module-tnd-redirects
  - path: github.com/theNewDynamic/hugo-module-tnd-icons
  - path: github.com/theNewDynamic/hugo-component-tnd-blocks
  - path: github.com/theNewDynamic/hugo-module-tnd-func
  - path: github.com/theNewDynamic/hugo-module-tnd-books
  # If we need iuebenda
  # - path: github.com/theNewDynamic/hugo-module-tnd-iubenda
