cloudcannon:
  collections:
    books:
      path: content/en/book
      _sort_key: title
      _subtext_key: role
      _singular_name: Book
      _singular_key: book
      _disable_add: 'false'
      _icon: book
      _add_options:
        name: Add New Book
        icon: book        

_collection_groups:
  - heading: Books
    collections:
      - book
      - review
  - heading: Updates
    collections:
      - news
      - post      
  - heading: Site
    collections:
      - pages      
