_collection_groups:
  - heading: Site
    collections:
      - page
  - heading: Publications
    collections:
      - books
      - reviews
      - articles
      - news
_editables:
  content:
    blockquote: true
    bold: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    bulletedlist: true
    indent: true
    numberedlist: true
    outdent: true
    code: false
    embed: true
    horizontalrule: true
    image: true
    table: false
    undo: true
    redo: true
    removeformat: true
    copyformatting: true
cloudcannon:
  collections:
    books:
      _singular_name: Book
      _singular_key: book
      _disable_add: false
      _icon: book
      _inputs: *cc_inputs
    reviews:
      _singular_name: Reviews
      _singular_key: review
      _disable_add: false
      _icon: text_format
      _inputs: *cc_inputs
    articles:
      _singular_name: Articles
      _singular_key: article
      _disable_add: false
      _icon: text_format
      _inputs: *cc_inputs
    news:
      _singular_name: News
      _singular_key: news
      _disable_add: false
      _icon: text_format