[build]
publish = "public"
command = "hugo -s _prebuild && hugo --minify"

[build.environment]
  GO_VERSION = "1.14"
  NODE_VERSION = "15.4.0"
  HUGO_VERSION = "0.108.0"
  SANITY_DATASET = "test"
[context]

[context.production]

[context.production.environment]
HUGO_ENV = "production"
SANITY_DATASET = "production"

[context.deploy-preview]
command = "hugo -s _prebuild && hugo --minify -D -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo -s _prebuild && hugo --minify -b $DEPLOY_URL"