caches:
  getresource:
    maxAge: 0
cleanDestinationDir: true
params:
  tnd_data:
    quiet: true
security:
  funcs:
    getenv:
    - ^HUGO_
    - ^SANITY_
module:
  imports:
  - path: github.com/theNewDynamic/hugo-module-tnd-data
  - path: github.com/theNewDynamic/huge
  mounts:
  - source: assets
    target: assets
  - source: ../_huge
    target: assets/_huge
  - source: ../content/en
    target: assets
  - source: ../assets/groq
    target: assets/groq
  - source: layouts
    target: layouts
  - source: ../layouts/partials
    target: layouts/partials
  - source: ../content/en
    target: layouts/partials
    excludeFiles: 
    - "**.md"